# Generated by Django 2.2.12 on 2020-04-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0003_auto_20200419_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dshop.Category', verbose_name='Родитель'),
        ),
    ]
