# Generated by Django 2.2.12 on 2020-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Название'),
        ),
    ]
