# Generated by Django 2.2.12 on 2020-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0007_auto_20200503_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
    ]
