# Generated by Django 2.2.12 on 2020-05-03 15:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0008_auto_20200503_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, verbose_name='Текст'),
        ),
    ]
