# Generated by Django 2.2.12 on 2020-05-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0011_auto_20200505_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
